env:
  n_nodes: 5
  max_steps: 150
  patch_delay_steps: 2

train:
  timesteps: 200000
  policy_by_algo:
    PPO: "MlpPolicy"
    DQN: "MlpPolicy"
    A2C: "MlpPolicy"
    QRDQN: "MlpPolicy"
    RecurrentPPO: "MlpLstmPolicy"
  model_kwargs: {}

eval:
  episodes: 200

seeds: [0, 1, 2, 3, 4]
