env:
  n_nodes: 10
  max_steps: 150
  patch_delay_steps: 2

  # make attacker slower
  p_adv_base: [0.03, 0.08, 0.08, 0.06, 0.0]
  zone_adv_mul:
    0: 1.05   # DMZ
    1: 0.95   # User
    2: 0.85   # Data
    3: 0.75   # Admin
    4: 0.60   # Security

  # make recovery stronger
  p_regress_base: 0.03
  p_quarantine_success: 0.90
  p_quarantine_roll_back_stage: 0.75
  p_patch_heal: 0.35

  intensity_drift: 0.015
  intensity_control_k: 0.12

  contain_hold_steps: 3

train:
  timesteps: 100000
  policy_by_algo:
    PPO: "MlpPolicy"
    DQN: "MlpPolicy"
    A2C: "MlpPolicy"
    QRDQN: "MlpPolicy"
    RecurrentPPO: "MlpLstmPolicy"

  model_kwargs_by_algo:
    PPO:
      learning_rate: 0.0003
      n_steps: 1024
      batch_size: 256
      gamma: 0.99
      gae_lambda: 0.95
      ent_coef: 0.01

    A2C:
      learning_rate: 0.0007
      n_steps: 64
      gamma: 0.99
      ent_coef: 0.01

    DQN:
      learning_rate: 0.0001
      buffer_size: 200000
      learning_starts: 5000
      train_freq: 4
      target_update_interval: 1000
      exploration_fraction: 0.2
      exploration_final_eps: 0.05

    QRDQN:
      learning_rate: 0.0001
      buffer_size: 200000
      learning_starts: 5000
      train_freq: 4
      target_update_interval: 1000
      exploration_fraction: 0.25
      exploration_final_eps: 0.05

    RecurrentPPO:
      learning_rate: 0.0003
      n_steps: 128
      batch_size: 128
      gamma: 0.99
      policy_kwargs:
        lstm_hidden_size: 128
        n_lstm_layers: 1

logging:
  log_root: "data/logs"
  tb_name: "AIRS_Enterprise"

eval:
  enabled: true
  freq: 20000           # evaluate every 20k steps
  n_episodes: 20
  early_stop_patience: 4   # stop after 4 evals with no improvement

seeds: [0, 1, 2, 3, 4]
